-- =====================================================================
-- DATOS MIGRADOS DE SQLITE A ORACLE
-- =====================================================================
-- Generado automáticamente
-- Fecha: 2026-01-15T23:26:11.511Z
-- =====================================================================


-- Tabla: users (15 registros)
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('HELDER MORA', 'Hmora', 'admin', NULL, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('ESTEFANIA RAMOS', 'Eramos', 'admin', NULL, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('ESTHFANIA RAMOS', 'Eramos', 'admin', NULL, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('FIERRO GALEANA ASAN ZZU', 'Exitus.cua', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('REYES CANO DULCE MARLEN', 'Exitus.ajh', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('BAEZ NIEVES SANDRA RUTH', 'Exitus.ayo', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('MORALES HERNANDEZ ROSALIA', 'Exitus.chi', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('GONZALEZ LOPEZ MARIA ISABEL', 'Exitus.ixt', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('MARTINEZ ZABALETA MARIELA SOLEDAD', 'Exitus.ver', 'tutor_analista', 45, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('ALFARO MARTINEZ KAREM JANETH', 'Exitus.tap', 'tutor_analista', 2, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('TORRES MEDINA MARIA ANTONIA', 'Exitus.tam', 'tutor_analista', 2, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('DE LA CRUZ JUAREZ KARLA MARINA', 'Exitus.apo', 'tutor_analista', 2, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('MONTOYA GARCIA CHRISTINE', 'Exitus.san', 'tutor_analista', 2, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('JIMENEZ HEREDIA JESSICA', 'Exitus.car', 'tutor_analista', 2, 1);
INSERT INTO users (username, password_hash, role, supervisor_id, branch_id) VALUES ('RODRIGUEZ SALAZAR ANA CARLOTA', 'Exitus.rod', 'tutor_analista', 2, 1);

-- Tabla: employees (171 registros)
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('IBAÑEZ VILLAGOMEZ GABRIELA', 4, '2024-02-09', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ZUBIETA BALAN ABIGAIL', 5, '2025-05-14', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SANTIAGO NOVELO KENIA ANDREA', 6, '2025-02-25', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ HERNANDEZ ARTEMISA', 7, '2025-05-28', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA MADRUEÑO MIRIAM', 8, '2024-01-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('TORRES BAUTISTA MARIA GUADALUPE', 9, '2019-01-23', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SANCHEZ OLVERA ANEL DANIELA', 10, '2024-08-23', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CAMACHO MARTINEZ BLANCA ORALIA', 11, '2024-03-25', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SALVADOR ABAD LESLIE', 12, '2024-01-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ CHAVEZ SELINA', 13, '2024-06-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ HERNANDEZ SOFIA', 14, '2025-02-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FERNANDEZ MIRANDA NATALY DEL CARMEN', 15, '2024-06-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SEGUNDO VILLEGAS EVELIN VANESA', 16, '2024-11-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RAMIREZ SANCHEZ ITZEL CARINA', 17, '2024-01-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GIL RIVERA LENIKA', 18, '2024-11-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ CORIA ERIKA', 19, '2023-02-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA GOMEZ LUCIA VIRGINIA', 20, '2024-10-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RAMIREZ HERNANDEZ DIANA LAURA', 21, '2025-02-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CABALLERO CABALLERO PAOLA JAQUELINE', 22, '2021-06-28', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LOZANO GOMEZ JOSELIN', 23, '2022-05-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ALFARO MARTINEZ KAREM JANETH', 24, '2018-12-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ARIAS RUIZ ROCIO', 25, '2025-01-23', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LOPEZ JIMENEZ ROSA AYDE', 26, '2020-07-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FLORES LOPEZ JENNIFER ESTEFANIA', 27, '2021-09-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('PALACIOS TOBIAS ANA GABRIELA', 28, '2020-03-25', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARES RODRIGUEZ LIZETH GUADALUPE', 28, '2024-09-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LOPEZ TORRES WENDI PALOMA', 29, '2025-05-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ CARRILLO SARELY NALLELY', 30, '2022-10-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA MAGALLANES KARLA ANAHI', 31, '2024-03-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ NUÑEZ YEIMY KEREN', 32, '2024-04-30', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ MONCAYO ARLEM DEL SOCORRO', 33, '2019-04-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RAMIREZ LORENZO MARIA YANET', 34, '2025-08-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORENO MARTINEZ ANA CELY', 35, '2023-06-09', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VELELA ROSALES DANIEL', 35, '2023-07-14', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ROSAS MEDRANO KENYA', 36, '2023-05-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('AGUILLON PINEDA TERESA', 37, '2025-08-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GODINEZ CORTEZ ARACELI', 38, '2015-06-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BASILIO GATICA ESTRELLA SINAI', 38, '2021-03-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CARLOS GONZALEZ MA. DOLORES', 39, '2025-02-18', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('REBOLLEDO HERNANDEZ HECTOR', 40, '2024-07-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FIERRO GALEANA ARANZAZU', 41, '2019-03-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA GUEVARA DENISE', 42, '2022-06-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('JIMENEZ PINEDA CAROLINA', 43, '2024-06-10', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('REYES CANO DULCE MARLEN', 44, '2020-08-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ORIHUELA TINAJERO ALMA LAURA', 45, '2014-07-18', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BARAJAS NOCHEBUENA MARICRUZ', 46, '2015-05-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SANCHEZ QUINTERO KAREN JAZMIN', 47, '2023-03-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ SALAZAR ANA CARLOTA', 48, '2013-06-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LINARES ALVAREZ MARCELA TERESA', 49, '2024-08-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BARRERA HERNANDEZ THALIA IVETTE', 50, '2013-06-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SALAZAR SANCHEZ BRENDA DELIA', 51, '2024-11-14', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('PEÑA MENDOZA KAREN IVONNE', 52, '2023-09-29', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ SANCHEZ GABRIELA', 53, '2025-01-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ TELLEZ ALEJANDRA', 54, '2020-03-05', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MELO ISLAS AIDE', 55, '2023-03-29', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ANTONIO CRUZ JOCELYN DEL CARMEN', 56, '2024-07-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RIOS REYES GABRIELA', 57, '2025-10-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VILLALPANDO ARREOLA MARISOL ANADELI', 58, '2020-12-10', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ CAPETILLO MONICA AHYDE', 59, '2017-09-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FLORES BRISEÑO ROCIO ALEJANDRA', 60, '2021-08-26', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MALDONADO GONZALEZ TANAIRI ADILENE', 61, '2025-06-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MALDONADO LOPEZ HECTOR MARIO', 62, '2024-10-31', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GERMAN BERNARDINO JANET', 63, '2025-05-09', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LORENZO MARTINEZ ALEXIA', 64, '2022-10-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BAEZ NIEVES SANDRA RUTH', 65, '2024-06-14', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ROJAS PEREZ MARBELL DE JESUS', 66, '2024-04-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORALES CHAVEZ MARIA GABRIELA', 67, '2025-04-30', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORALES HERNANDEZ ROSALIA', 68, '2024-04-17', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GOMEZ SERVIN MARIA DEL CARMEN', 69, '2024-01-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CABRERA BOHORQUEZ OSCAR DAVID', 70, '2025-02-10', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ RUIZ PERLA RUTH', 71, '2024-06-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GONZALEZ LOPEZ MARIA ISABEL', 72, '2022-05-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GOMEZ RIVERA SUSANA DENICE', 73, '2020-11-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SANCHEZ ALVAREZ DIANA CITLALLI', 74, '2025-09-10', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('NICOLAS ARMENDARIZ MARIANA', 75, '2024-01-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA VAZQUEZ MIRIAM LORENA', 76, '2025-03-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ FLORES DORISELA JULISSA', 77, '2025-10-31', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ MADRIGAL MARIBEL CLEMENTINA', 78, '2024-06-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ANGELES ALEGRIA LILIANA', 79, '2024-11-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ MERCADO VANESSA ALEXEY', 80, '2025-01-28', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORENO DE PAZ MARIA GUADALUPE', 81, '2025-07-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ZAMORA VARELA YANELY ALEJANDRA', 82, '2024-01-31', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RODRIGUEZ GARCIA ROCIO', 83, '2017-10-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BARRAGAN CHAVEZ MARIELA MONTSERRAT', 84, '2019-11-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RIVERA CARRILLO GLADYS ISABEL', 84, '2022-12-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FLORES CHAVEZ LAURA ELISA', 85, '2021-09-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VELAZQUEZ VILLA MARIELA', 85, '2025-07-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('REYES FRASCO MARIA ELIZABETH', 86, '2023-06-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ORTIZ SANCHEZ GABRIELA', 87, '2025-09-02', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VELEZ GONZALEZ ADILENE', 88, '2025-05-27', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('JIMENEZ RIOS ENRIQUE', 89, '2025-11-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ALVAREZ ZAVALA VIRGINIA', 90, '2023-08-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CORONA ROSALES GISEL', 91, '2021-11-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MADRIGAL GAMIÑO JOSE LUIS', 92, '2023-10-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ MORALES CATALINA ENRIQUETA', 93, '2022-01-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('AMBRIZ CARRANZA ANA JANETH', 94, '2013-06-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ RODRIGUEZ SUSANA', 94, '2016-12-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ORTIZ BARRAGAN BRENDA BERENICE', 95, '2013-06-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('OCAMPO FRANCISCO ELIZABETH', 96, '2024-06-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RIVERA SAMANO NAYELI', 97, '2021-05-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ROBLES ROXANA GUADALUPE', 98, '2024-12-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CARVAJAL AVILA RAFAEL', 99, '2021-01-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('DE LA CRUZ JUAREZ KARLA MARINA', 100, '2025-06-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CASTRO MENA YADIRA MARISOL', 101, '2022-03-16', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MONTEMAYOR LOPEZ CITLALY JARETH', 102, '2025-01-17', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LAZARO RUBIO CINTHIA NELLY', 103, '2025-09-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LOPEZ HERNANDEZ SONIA', 104, '2015-04-21', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CRUZ CASTRO ANA MELISSA', 105, '2023-10-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CARRILLO RENOVATO DALIA DENISSE', 106, '2025-03-28', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ RODRIGUEZ PERLA CECILIA', 107, '2020-11-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CAVAZOS ESCALON ELIUD IZAI', 107, '2024-02-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SORIANO SORIANO ROSELI', 108, '2022-06-25', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MEDINA TORRES LILIANA GUADALUPE', 109, '2022-11-11', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('FIGUEROA GARCIA KARINA DENISSE', 110, '2023-01-13', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA SANCHEZ MITZY', 111, '2023-05-13', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('BADO HERNANDEZ KARLA', 112, '2016-06-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ROBELO GARCIA MARIA MAGDALENA', 113, '2022-05-17', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ESCALANTE ROJANO ROSA ADRIANA', 114, '2025-02-17', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RAMIREZ MORALES SUSANA', 115, '2022-01-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('JARAMILLO GONZALEZ NORMA ELDA', 115, '2025-04-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ CARRERA ADRIANA', 116, '2024-01-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('AC UITZIL NALLELY GERALDINY', 117, '2020-11-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ORDOÑEZ MEDINA NADIEZHDA JEUDALI', 118, '2023-06-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('UC CABRERA MARISOL', 119, '2021-05-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORALES LIMON JOHANNA ELIZABETH', 120, '2021-05-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GUERRERO LUCANO WENDY LOURDES', 121, '2025-02-27', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA LOPEZ MAYRA ALEJANDRA', 122, '2021-02-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VARGAS LAZCANO LIBIA KIZLETH', 123, '2020-08-31', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('IBARRA VARGAS MARIA TERESA', 124, '2014-03-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('AHUMADA ALVAREZ REBECA', 125, '2025-10-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ZAMARRIPA MARTINEZ RAQUEL', 126, '2025-01-21', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MONTOYA GARCIA CHRISTINE', 127, '2018-01-02', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ZUÑIGA ZUÑIGA ANA MARIA', 127, '2024-02-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ MARQUEZ ROSA MARIA', 128, '2023-09-05', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ROMAN ACOSTA ROXANA IVETH', 129, '2023-08-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VALENZUELA SALMON JESUS FRANCISCO', 130, '2025-01-29', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('PERALTA VALENZUELA KARLA PATRICIA', 131, '2019-04-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('DE LA PAZ CHAVEZ KARLA KAREN', 132, '2025-07-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('OSUNA ARIAS MARIA DE JESUS', 133, '2024-11-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CEFERINO PIEDRA ERIKA', 134, '2014-07-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('JIMENEZ HEREDIA JESSICA', 135, '2019-10-09', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ALBERTO ALMEIDA LAURA', 136, '2024-08-05', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MADRIGAL OLAN MARIA JOCELYN', 137, '2024-04-02', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GONZALEZ MAGAÑA ANA KAREN', 138, '2024-10-08', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA LOZANO MARIANA YITZEL', 139, '2023-12-29', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CANO LUMBRERAS DIANA LAURA', 140, '2022-02-17', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('TORRES MEDINA MARIA ANTONIA', 141, '2018-03-05', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CERVANTES ALCOCER DEBORA PATRICIA', 142, '2025-08-07', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('LOPEZ CRUZ JOHANNA', 143, '2019-05-09', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('ARELLANO OJEDA ARELI', 144, '2025-11-27', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('DOMINGUEZ ZEFERINO MAYDA PAOLA', 145, '2022-10-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('GARCIA LEYVA ALONDRA MARIANA', 146, '2020-11-03', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SANTOS OCHOA BLANCA ICELA', 147, '2023-01-06', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CRUZ CASTILLEJOS ANA KAREN', 148, '2017-11-02', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CASTILLO ROMAN LORENA', 149, '2014-05-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('PREZA URRUTIA PATRICIA', 150, '2023-10-02', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('NAVARRETE TENORIO EUNICE YANELLY', 151, '2019-11-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MORELOS SALAS LILIANA', 152, '2021-05-12', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CRUZ MONTERO ALMA ERIKA', 153, '2017-11-19', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ VALLADARES CITLALY NALLELY', 154, '2021-06-01', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('HERNANDEZ TORRES SINDY ANABEL', 155, '2025-10-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SEBASTIAN CASTRO KAREN ABIGAID', 156, '2024-01-10', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('SOLIS AGUILAR MAYRA', 156, '2025-07-31', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('PIXTA RAZO LIZETTE DEL CARMEN', 157, '2024-04-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('RAMOS CRUZ ARACELI', 158, '2023-02-14', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ AGUILAR SANDY', 159, '2024-09-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('MARTINEZ ZABALETA MARIELA SOLEDAD', 160, '2021-10-22', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CHAGALA CARVALLO LUCERO', 161, '2020-12-04', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('EMETERIO ESPINOSA DIANA', 162, '2025-01-24', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('VAZQUEZ APARICIO ALEJANDRA', 163, '2019-09-13', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('CHI MANZANO CINTHYA YAMILI', 164, '2023-12-28', 'active');

-- Tabla: attendance_roster (6 registros)
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (96, 2);
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (130, 57);
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (122, 57);
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (21, 57);
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (116, 52);
INSERT INTO attendance_roster (employee_id, added_by_user_id) VALUES (22, 52);

-- Tabla: attendance (8 registros)
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (1, '2026-01-01', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (122, '2025-12-01', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (84, '2026-01-01', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (84, '2026-01-02', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (84, '2026-01-03', 'delay', NULL, '09:09', NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (84, '2026-01-04', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (84, '2026-01-05', 'present', NULL, NULL, NULL, NULL, NULL);
INSERT INTO attendance (employee_id, date, status, comment, arrival_time, permission_type, start_date, end_date) VALUES (122, '2026-01-01', 'delay', 'COMENTA QUE CERRARIN LA CALLE LOS CAMPESINOS ', '09:01', NULL, NULL, NULL);

-- Tabla: reports (3 registros)
INSERT INTO reports (employee_id, month, year, data) VALUES (122, 0, 2026, '{"faltantes":{"1":{"status":"check","comment":""},"2":{"status":"check","comment":""}},"guias":{},"tableros":{}}');
INSERT INTO reports (employee_id, month, year, data) VALUES (130, 0, 2026, '{"faltantes":{"1":{"status":"check","comment":""},"2":{"status":"check","comment":""},"3":{"status":"cross","comment":"PERMISO PARA IR AL DOCTOR"},"4":{"status":"check","comment":""},"5":{"status":"check","comment":""},"6":{"status":"check","comment":""},"7":{"status":"check","comment":""}},"guias":{},"tableros":{}}');
INSERT INTO reports (employee_id, month, year, data) VALUES (84, 0, 2026, '{"faltantes":{"1":{"status":"check","comment":""},"2":{"status":"check","comment":""}},"guias":{"1":{"status":"check","comment":""}},"tableros":{}}');

COMMIT;

PROMPT ✅ Datos importados exitosamente
