-- Oracle Schema
-- User/Schema creation is assumed handled (USER gestion_tutor implied or current schema)

-- Branches Table
CREATE TABLE branches (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(255)
);

-- Users Table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) CHECK (role IN ('admin', 'tutor_analista', 'gerente', 'rrhh', 'soporte')) NOT NULL,
    branch_id NUMBER REFERENCES branches(id),
    supervisor_id NUMBER REFERENCES users(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Employees Table
CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    branch_id NUMBER REFERENCES branches(id),
    hire_date VARCHAR2(20), -- Storing as string to match SQLite logic
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'vacation', 'sick_leave')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Attendance Roster (Missing in original schema.sql but used in server.js)
CREATE TABLE attendance_roster (
    employee_id NUMBER PRIMARY KEY REFERENCES employees(id)
);

-- Attendance (referenced in server.js, not in schema.sql? It must be created somewhere)
-- Based on server.js usage:
CREATE TABLE attendance (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER REFERENCES employees(id),
    date VARCHAR2(20), -- 'YYYY-MM-DD'
    status VARCHAR2(20),
    comment VARCHAR2(4000),
    arrival_time VARCHAR2(10),
    permission_type VARCHAR2(50),
    start_date VARCHAR2(20),
    end_date VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Incidents Table
CREATE TABLE incidents (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_id NUMBER NOT NULL REFERENCES branches(id),
    reported_by NUMBER NOT NULL REFERENCES users(id),
    type VARCHAR2(20) CHECK (type IN ('luz', 'internet', 'equipo', 'correo', 'otro')) NOT NULL,
    description CLOB,
    status VARCHAR2(20) DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved')),
    start_date VARCHAR2(20),
    end_date VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Reports Table
CREATE TABLE reports (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL REFERENCES employees(id),
    month NUMBER,
    year NUMBER,
    data CLOB, -- JSON string
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- Seed Data (Branches)
INSERT INTO branches (name, location) VALUES ('Corporativo', 'CDMX');
INSERT INTO branches (name, location) VALUES ('Sucursal Norte', 'Monterrey');
INSERT INTO branches (name, location) VALUES ('Sucursal Sur', 'Guadalajara');
COMMIT;
