-- =============================================================================
-- SCRIPT COMPLETO DE CONFIGURACIÓN DE ORACLE ORDS (API REST SERVERLESS)
-- =============================================================================
-- Este script crea las tablas, inserta datos iniciales y configura TODOS los servicios REST.
-- Ejecuta este script en "Database Actions -> SQL" (SQL Developer Web) en Oracle Cloud.
-- =============================================================================

-- 1. CREACIÓN DE TABLAS (SCHEMA)
-- =============================================================================

-- Sucursales
CREATE TABLE branches (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(255)
);

-- Usuarios
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'tutor_analista' CHECK (role IN ('admin', 'tutor_analista', 'gerente', 'rrhh', 'soporte')),
    branch_id NUMBER,
    supervisor_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_users_supervisor FOREIGN KEY (supervisor_id) REFERENCES users(id)
);

-- Empleados
CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    branch_id NUMBER,
    hire_date DATE,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'vacation', 'sick_leave')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
);

-- Incidencias
CREATE TABLE incidents (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_id NUMBER NOT NULL,
    reported_by NUMBER NOT NULL,
    type VARCHAR2(50) NOT NULL,
    description CLOB,
    status VARCHAR2(50) DEFAULT 'EN PROCESO',
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inc_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_inc_reporter FOREIGN KEY (reported_by) REFERENCES employees(id)
);

-- Reportes Diarios
CREATE TABLE reports (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_id NUMBER,
    user_id NUMBER,
    month NUMBER,
    year NUMBER,
    data CLOB, -- JSON Stored as Text
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rep_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_rep_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Asistencia
CREATE TABLE attendance (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    date_mark DATE NOT NULL,
    status VARCHAR2(20),
    comment_text VARCHAR2(4000),
    arrival_time VARCHAR2(20),
    permission_type VARCHAR2(50),
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_att_emp FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Lista de Asistencia (Roster)
CREATE TABLE attendance_roster (
    employee_id NUMBER PRIMARY KEY,
    CONSTRAINT fk_rost_emp FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- =============================================================================
-- 2. DATOS INICIALES (SEED DATA)
-- =============================================================================

INSERT INTO branches (name, location) VALUES ('Corporativo', 'CDMX');
INSERT INTO branches (name, location) VALUES ('Sucursal Norte', 'Monterrey');
INSERT INTO branches (name, location) VALUES ('Sucursal Sur', 'Guadalajara');

-- Admin User
INSERT INTO users (username, password_hash, role, branch_id) VALUES ('admin', 'admin123', 'admin', 1);

-- Empleados de ejemplo
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('Juan Pérez', 1, DATE '2023-01-15', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('María García', 2, DATE '2023-02-20', 'active');
INSERT INTO employees (full_name, branch_id, hire_date, status) VALUES ('Carlos López', 3, DATE '2023-03-10', 'active');

COMMIT;

-- =============================================================================
-- 3. HABILITACIÓN DE ORDS (REST APIs)
-- =============================================================================
BEGIN
    ORDS.ENABLE_SCHEMA(
        p_enabled             => TRUE,
        p_schema              => USER,
        p_url_mapping_type    => 'BASE_PATH',
        p_url_mapping_pattern => 'admin',
        p_auto_rest_auth      => FALSE
    );
    COMMIT;
END;
/

-- Definición del Módulo API
BEGIN
    ORDS.DEFINE_MODULE(
        p_module_name    => 'api',
        p_base_path      => 'api/v1/',
        p_items_per_page => 100,
        p_status         => 'PUBLISHED',
        p_comments       => 'API para Gestion Tutor Analista'
    );
    
    -- =========================================================================
    -- ENDPOINT: LOGIN (POST)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'login'
    );
    
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'login',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body    BLOB;
    l_json    JSON_OBJECT_T;
    l_user    VARCHAR2(50);
    l_pass    VARCHAR2(50);
    l_id      NUMBER;
    l_role    VARCHAR2(50);
    l_branch  NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    l_user := l_json.get_String(''username'');
    l_pass := l_json.get_String(''password'');
    
    SELECT id, role, branch_id 
    INTO l_id, l_role, l_branch
    FROM users 
    WHERE username = l_user AND password_hash = l_pass;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Bienvenido'');
    APEX_JSON.open_object(''user'');
    APEX_JSON.write(''id'', l_id);
    APEX_JSON.write(''username'', l_user);
    APEX_JSON.write(''role'', l_role);
    APEX_JSON.write(''branch_id'', l_branch);
    APEX_JSON.close_object;
    APEX_JSON.close_object;
EXCEPTION WHEN NO_DATA_FOUND THEN
    :status_code := 401;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', ''Usuario o contraseña incorrectos'');
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: EMPLOYEES (GET ALL)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'employees'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'employees',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
BEGIN
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_array(''data'');
    
    FOR r IN (SELECT e.id, e.full_name, e.branch_id, e.hire_date, e.status, b.name as branch_name 
              FROM employees e 
              LEFT JOIN branches b ON e.branch_id = b.id
              ORDER BY e.full_name ASC) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id'', r.id);
        APEX_JSON.write(''full_name'', r.full_name);
        APEX_JSON.write(''branch_id'', r.branch_id);
        APEX_JSON.write(''branch_name'', r.branch_name);
        APEX_JSON.write(''hire_date'', TO_CHAR(r.hire_date, ''YYYY-MM-DD''));
        APEX_JSON.write(''status'', r.status);
        APEX_JSON.close_object;
    END LOOP;
    
    APEX_JSON.close_array;
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: EMPLOYEES (POST - Create)
    -- =========================================================================
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'employees',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body       BLOB;
    l_json       JSON_OBJECT_T;
    l_name       VARCHAR2(100);
    l_branch_id  NUMBER;
    l_hire_date  DATE;
    l_new_id     NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    l_name := l_json.get_String(''full_name'');
    l_branch_id := l_json.get_Number(''branch_id'');
    
    IF l_json.has(''hire_date'') THEN
        l_hire_date := TO_DATE(l_json.get_String(''hire_date''), ''YYYY-MM-DD'');
    END IF;
    
    INSERT INTO employees (full_name, branch_id, hire_date, status)
    VALUES (l_name, l_branch_id, l_hire_date, ''active'')
    RETURNING id INTO l_new_id;
    
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Empleado creado correctamente'');
    APEX_JSON.write(''id'', l_new_id);
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: EMPLOYEES/:id (DELETE)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'employees/:id'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'employees/:id',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_id NUMBER := :id;
BEGIN
    DELETE FROM employees WHERE id = l_id;
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Empleado eliminado correctamente'');
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: BRANCHES (GET ALL)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'branches'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'branches',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
BEGIN
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_array(''data'');
    
    FOR r IN (SELECT id, name, location FROM branches ORDER BY name) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id'', r.id);
        APEX_JSON.write(''name'', r.name);
        APEX_JSON.write(''location'', r.location);
        APEX_JSON.close_object;
    END LOOP;
    
    APEX_JSON.close_array;
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: INCIDENTS (GET ALL)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'incidents'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'incidents',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
BEGIN
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_array(''data'');
    
    FOR r IN (SELECT i.id, i.branch_id, i.reported_by, i.type, i.description, i.status, 
                     i.start_date, i.end_date, i.created_at,
                     b.name as branch_name, e.full_name as reported_by_name
              FROM incidents i
              LEFT JOIN branches b ON i.branch_id = b.id
              LEFT JOIN employees e ON i.reported_by = e.id
              ORDER BY i.created_at DESC) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id'', r.id);
        APEX_JSON.write(''branch_id'', r.branch_id);
        APEX_JSON.write(''branch_name'', r.branch_name);
        APEX_JSON.write(''reported_by'', r.reported_by);
        APEX_JSON.write(''reported_by_name'', r.reported_by_name);
        APEX_JSON.write(''type'', r.type);
        APEX_JSON.write(''description'', r.description);
        APEX_JSON.write(''status'', r.status);
        APEX_JSON.write(''start_date'', TO_CHAR(r.start_date, ''YYYY-MM-DD''));
        APEX_JSON.write(''end_date'', TO_CHAR(r.end_date, ''YYYY-MM-DD''));
        APEX_JSON.close_object;
    END LOOP;
    
    APEX_JSON.close_array;
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: INCIDENTS (POST - Create)
    -- =========================================================================
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'incidents',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body        BLOB;
    l_json        JSON_OBJECT_T;
    l_emp_id      NUMBER;
    l_type        VARCHAR2(50);
    l_status      VARCHAR2(50);
    l_start_date  DATE;
    l_end_date    DATE;
    l_desc        CLOB;
    l_branch_id   NUMBER;
    l_new_id      NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    
    l_emp_id := l_json.get_Number(''employee_id'');
    l_type := l_json.get_String(''type'');
    l_status := l_json.get_String(''status'');
    
    IF l_json.has(''start_date'') AND l_json.get_String(''start_date'') IS NOT NULL THEN
        l_start_date := TO_DATE(l_json.get_String(''start_date''), ''YYYY-MM-DD'');
    END IF;
    
    IF l_json.has(''end_date'') AND l_json.get_String(''end_date'') IS NOT NULL THEN
        l_end_date := TO_DATE(l_json.get_String(''end_date''), ''YYYY-MM-DD'');
    END IF;
    
    IF l_json.has(''description'') THEN
        l_desc := l_json.get_String(''description'');
    END IF;
    
    -- Get branch_id from employee
    SELECT branch_id INTO l_branch_id FROM employees WHERE id = l_emp_id;
    
    INSERT INTO incidents (branch_id, reported_by, type, description, status, start_date, end_date)
    VALUES (l_branch_id, l_emp_id, l_type, l_desc, l_status, l_start_date, l_end_date)
    RETURNING id INTO l_new_id;
    
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Incidencia creada correctamente'');
    APEX_JSON.write(''id'', l_new_id);
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: INCIDENTS/:id (PUT - Update)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'incidents/:id'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'incidents/:id',
        p_method         => 'PUT',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_id          NUMBER := :id;
    l_body        BLOB;
    l_json        JSON_OBJECT_T;
    l_emp_id      NUMBER;
    l_type        VARCHAR2(50);
    l_status      VARCHAR2(50);
    l_start_date  DATE;
    l_end_date    DATE;
    l_desc        CLOB;
    l_branch_id   NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    
    l_emp_id := l_json.get_Number(''employee_id'');
    l_type := l_json.get_String(''type'');
    l_status := l_json.get_String(''status'');
    
    IF l_json.has(''start_date'') AND l_json.get_String(''start_date'') IS NOT NULL THEN
        l_start_date := TO_DATE(l_json.get_String(''start_date''), ''YYYY-MM-DD'');
    END IF;
    
    IF l_json.has(''end_date'') AND l_json.get_String(''end_date'') IS NOT NULL THEN
        l_end_date := TO_DATE(l_json.get_String(''end_date''), ''YYYY-MM-DD'');
    END IF;
    
    IF l_json.has(''description'') THEN
        l_desc := l_json.get_String(''description'');
    END IF;
    
    -- Get branch_id from employee
    SELECT branch_id INTO l_branch_id FROM employees WHERE id = l_emp_id;
    
    UPDATE incidents 
    SET branch_id = l_branch_id,
        reported_by = l_emp_id,
        type = l_type,
        description = l_desc,
        status = l_status,
        start_date = l_start_date,
        end_date = l_end_date
    WHERE id = l_id;
    
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Incidencia actualizada correctamente'');
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: INCIDENTS/:id (DELETE)
    -- =========================================================================
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'incidents/:id',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_id NUMBER := :id;
BEGIN
    DELETE FROM incidents WHERE id = l_id;
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Incidencia eliminada correctamente'');
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: ATTENDANCE/MARK (POST)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'attendance/mark'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'attendance/mark',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body           BLOB;
    l_json           JSON_OBJECT_T;
    l_emp_id         NUMBER;
    l_date           DATE;
    l_status         VARCHAR2(20);
    l_comment        VARCHAR2(4000);
    l_arrival_time   VARCHAR2(20);
    l_perm_type      VARCHAR2(50);
    l_start_date     DATE;
    l_end_date       DATE;
    l_existing_id    NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    
    l_emp_id := l_json.get_Number(''employee_id'');
    l_date := TO_DATE(l_json.get_String(''date''), ''YYYY-MM-DD'');
    l_status := l_json.get_String(''status'');
    
    IF l_json.has(''comment'') THEN l_comment := l_json.get_String(''comment''); END IF;
    IF l_json.has(''arrival_time'') THEN l_arrival_time := l_json.get_String(''arrival_time''); END IF;
    IF l_json.has(''permission_type'') THEN l_perm_type := l_json.get_String(''permission_type''); END IF;
    IF l_json.has(''start_date'') AND l_json.get_String(''start_date'') IS NOT NULL THEN 
        l_start_date := TO_DATE(l_json.get_String(''start_date''), ''YYYY-MM-DD''); 
    END IF;
    IF l_json.has(''end_date'') AND l_json.get_String(''end_date'') IS NOT NULL THEN 
        l_end_date := TO_DATE(l_json.get_String(''end_date''), ''YYYY-MM-DD''); 
    END IF;
    
    -- Check if attendance already exists
    BEGIN
        SELECT id INTO l_existing_id 
        FROM attendance 
        WHERE employee_id = l_emp_id AND date_mark = l_date;
        
        -- Update existing
        UPDATE attendance 
        SET status = l_status,
            comment_text = l_comment,
            arrival_time = l_arrival_time,
            permission_type = l_perm_type,
            start_date = l_start_date,
            end_date = l_end_date
        WHERE id = l_existing_id;
    EXCEPTION WHEN NO_DATA_FOUND THEN
        -- Insert new
        INSERT INTO attendance (employee_id, date_mark, status, comment_text, arrival_time, permission_type, start_date, end_date)
        VALUES (l_emp_id, l_date, l_status, l_comment, l_arrival_time, l_perm_type, l_start_date, l_end_date);
    END;
    
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Asistencia guardada correctamente'');
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: ATTENDANCE/ROSTER (GET)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'attendance/roster'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'attendance/roster',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
BEGIN
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_array(''data'');
    
    FOR r IN (SELECT e.id, e.full_name, b.name as branch_name
              FROM attendance_roster ar
              JOIN employees e ON ar.employee_id = e.id
              LEFT JOIN branches b ON e.branch_id = b.id
              ORDER BY e.full_name) LOOP
        APEX_JSON.open_object;
        APEX_JSON.write(''id'', r.id);
        APEX_JSON.write(''full_name'', r.full_name);
        APEX_JSON.write(''branch_name'', r.branch_name);
        APEX_JSON.close_object;
    END LOOP;
    
    APEX_JSON.close_array;
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: ATTENDANCE/ROSTER (POST - Add to roster)
    -- =========================================================================
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'attendance/roster',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body    BLOB;
    l_json    JSON_OBJECT_T;
    l_emp_id  NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    l_emp_id := l_json.get_Number(''employee_id'');
    
    INSERT INTO attendance_roster (employee_id) VALUES (l_emp_id);
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Colaborador agregado a la lista'');
    APEX_JSON.close_object;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', ''El colaborador ya está en la lista'');
    APEX_JSON.close_object;
WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: ATTENDANCE/ROSTER/:id (DELETE - Remove from roster)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'attendance/roster/:id'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'attendance/roster/:id',
        p_method         => 'DELETE',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_id NUMBER := :id;
BEGIN
    DELETE FROM attendance_roster WHERE employee_id = l_id;
    COMMIT;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Colaborador eliminado de la lista'');
    APEX_JSON.close_object;
EXCEPTION WHEN OTHERS THEN
    ROLLBACK;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', SQLERRM);
    APEX_JSON.close_object;
END;'
    );

    -- =========================================================================
    -- ENDPOINT: DASHBOARD STATS (GET)
    -- =========================================================================
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'dashboard/stats'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'dashboard/stats',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_asist NUMBER := 0;
    l_faltas NUMBER := 0;
    l_vacas NUMBER := 0;
    l_perm NUMBER := 0;
    l_incap NUMBER := 0;
    l_incid NUMBER := 0;
BEGIN
    -- Calc stats for TODAY
    FOR r IN (SELECT status, COUNT(*) c FROM attendance WHERE TRUNC(date_mark) = TRUNC(SYSDATE) GROUP BY status) LOOP
        IF r.status = ''present'' THEN l_asist := r.c;
        ELSIF r.status = ''absent'' THEN l_faltas := r.c;
        ELSIF r.status = ''vacation'' THEN l_vacas := r.c;
        ELSIF r.status = ''permission'' THEN l_perm := r.c;
        ELSIF r.status = ''incapacity'' THEN l_incap := r.c;
        END IF;
    END LOOP;
    
    SELECT COUNT(*) INTO l_incid FROM incidents WHERE status IN (''EN PROCESO'', ''SIN RESPUESTA'');
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_object(''data'');
    APEX_JSON.write(''asistencias'', l_asist);
    APEX_JSON.write(''faltas'', l_faltas);
    APEX_JSON.write(''vacaciones'', l_vacas);
    APEX_JSON.write(''permisos'', l_perm);
    APEX_JSON.write(''incapacidades'', l_incap);
    APEX_JSON.write(''incidencias_activas'', l_incid);
    APEX_JSON.close_object;
    APEX_JSON.close_object;
END;'
    );
    
    COMMIT;
END;
/

-- =============================================================================
-- 4. VERIFICACIÓN
-- =============================================================================
SELECT * FROM user_ords_modules;
SELECT * FROM user_ords_templates;
SELECT * FROM user_ords_handlers;
