-- =============================================================================
-- SCRIPT DE CONFIGURACIÓN DE ORACLE ORDS (API REST SERVERLESS)
-- =============================================================================
-- Este script crea las tablas, inserta datos iniciales y configura los servicios REST.
-- Ejecuta este script en "Database Actions -> SQL" (SQL Developer Web) en Oracle Cloud.
-- =============================================================================

-- 1. CREACIÓN DE TABLAS (SCHEMA)
-- =============================================================================

-- Sucursales
CREATE TABLE branches (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(255)
);

-- Usuarios
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(50) DEFAULT 'tutor_analista' CHECK (role IN ('admin', 'tutor_analista', 'gerente', 'rrhh', 'soporte')),
    branch_id NUMBER,
    supervisor_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_users_supervisor FOREIGN KEY (supervisor_id) REFERENCES users(id)
);

-- Empleados
CREATE TABLE employees (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    branch_id NUMBER,
    hire_date DATE,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'vacation', 'sick_leave')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_emp_branch FOREIGN KEY (branch_id) REFERENCES branches(id)
);

-- Incidencias
CREATE TABLE incidents (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_id NUMBER NOT NULL,
    reported_by NUMBER NOT NULL,
    type VARCHAR2(50) NOT NULL,
    description CLOB,
    status VARCHAR2(20) DEFAULT 'open',
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inc_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_inc_reporter FOREIGN KEY (reported_by) REFERENCES users(id)
);

-- Reportes Diarios
CREATE TABLE reports (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    branch_id NUMBER,
    user_id NUMBER,
    month NUMBER,
    year NUMBER,
    data CLOB, -- JSON Stored as Text
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rep_branch FOREIGN KEY (branch_id) REFERENCES branches(id),
    CONSTRAINT fk_rep_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Asistencia
CREATE TABLE attendance (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    date_mark DATE NOT NULL, -- Renamed from 'date' to avoid keyword conflict
    status VARCHAR2(20),
    comment_text VARCHAR2(4000), -- 'comment' is a keyword
    arrival_time VARCHAR2(20),
    permission_type VARCHAR2(50),
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_att_emp FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- Lista de Asistencia (Roster)
CREATE TABLE attendance_roster (
    employee_id NUMBER PRIMARY KEY,
    CONSTRAINT fk_rost_emp FOREIGN KEY (employee_id) REFERENCES employees(id)
);

-- =============================================================================
-- 2. DATOS INICIALES (SEED DATA)
-- =============================================================================

INSERT INTO branches (name, location) VALUES ('Corporativo', 'CDMX');
INSERT INTO branches (name, location) VALUES ('Sucursal Norte', 'Monterrey');
INSERT INTO branches (name, location) VALUES ('Sucursal Sur', 'Guadalajara');

-- Admin User
INSERT INTO users (username, password_hash, role, branch_id) VALUES ('admin', 'admin123', 'admin', 1);

COMMIT;

-- =============================================================================
-- 3. HABILITACIÓN DE ORDS (REST APIs)
-- =============================================================================
BEGIN
    ORDS.ENABLE_SCHEMA(
        p_enabled             => TRUE,
        p_schema              => USER,
        p_url_mapping_type    => 'BASE_PATH',
        p_url_mapping_pattern => 'gestion_app', -- URL será .../ords/gestion_app/...
        p_auto_rest_auth      => FALSE
    );
    COMMIT;
END;
/

-- Definición del Módulo API
BEGIN
    ORDS.DEFINE_MODULE(
        p_module_name    => 'api',
        p_base_path      => 'api/',
        p_items_per_page => 100,
        p_status         => 'PUBLISHED',
        p_comments       => 'API para Gestion Tutor Analista'
    );
    
    -- -----------------------------------------------------------------------------
    -- ENDPOINT: LOGIN (POST)
    -- Recibe: { "username": "...", "password": "..." }
    -- Retorna: User Object o 401
    -- -----------------------------------------------------------------------------
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'login'
    );
    
    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'login',
        p_method         => 'POST',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_body    BLOB;
    l_json    JSON_OBJECT_T;
    l_user    VARCHAR2(50);
    l_pass    VARCHAR2(50);
    l_id      NUMBER;
    l_role    VARCHAR2(50);
    l_branch  NUMBER;
BEGIN
    l_body := :body;
    l_json := JSON_OBJECT_T(l_body);
    l_user := l_json.get_String(''username'');
    l_pass := l_json.get_String(''password'');
    
    SELECT id, role, branch_id 
    INTO l_id, l_role, l_branch
    FROM users 
    WHERE username = l_user AND password_hash = l_pass;
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.write(''message'', ''Bienvenido'');
    APEX_JSON.open_object(''user'');
    APEX_JSON.write(''id'', l_id);
    APEX_JSON.write(''username'', l_user);
    APEX_JSON.write(''role'', l_role);
    APEX_JSON.write(''branch_id'', l_branch);
    APEX_JSON.close_object;
    APEX_JSON.close_object;
EXCEPTION WHEN NO_DATA_FOUND THEN
    :status_code := 401;
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', false);
    APEX_JSON.write(''message'', ''Usuario o contraseña incorrectos'');
    APEX_JSON.close_object;
END;'
    );

    -- -----------------------------------------------------------------------------
    -- ENDPOINT: EMPLOYEES (GET)
    -- -----------------------------------------------------------------------------
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'employees'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'employees',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_collection_feed,
        p_source         => 'SELECT e.id, e.full_name, e.branch_id, e.hire_date, e.status, b.name as branch_name 
                             FROM employees e 
                             LEFT JOIN branches b ON e.branch_id = b.id
                             ORDER BY e.full_name ASC'
    );

    -- -----------------------------------------------------------------------------
    -- ENDPOINT: DASHBOARD STATS (GET)
    -- -----------------------------------------------------------------------------
    ORDS.DEFINE_TEMPLATE(
        p_module_name    => 'api',
        p_pattern        => 'dashboard/stats'
    );

    ORDS.DEFINE_HANDLER(
        p_module_name    => 'api',
        p_pattern        => 'dashboard/stats',
        p_method         => 'GET',
        p_source_type    => ORDS.source_type_plsql,
        p_source         => '
DECLARE
    l_asist NUMBER := 0;
    l_faltas NUMBER := 0;
    l_vacas NUMBER := 0;
    l_perm NUMBER := 0;
    l_incap NUMBER := 0;
    l_incid NUMBER := 0;
BEGIN
    -- Calc stats for TODAY
    FOR r IN (SELECT status, COUNT(*) c FROM attendance WHERE TRUNC(date_mark) = TRUNC(SYSDATE) GROUP BY status) LOOP
        IF r.status = ''present'' THEN l_asist := r.c;
        ELSIF r.status = ''absent'' THEN l_faltas := r.c;
        ELSIF r.status = ''vacation'' THEN l_vacas := r.c;
        ELSIF r.status = ''permission'' THEN l_perm := r.c;
        ELSIF r.status = ''incapacity'' THEN l_incap := r.c;
        END IF;
    END LOOP;
    
    SELECT COUNT(*) INTO l_incid FROM incidents WHERE status IN (''pending'', ''in_progress'');
    
    APEX_JSON.open_object;
    APEX_JSON.write(''success'', true);
    APEX_JSON.open_object(''data'');
    APEX_JSON.write(''asistencias'', l_asist);
    APEX_JSON.write(''faltas'', l_faltas);
    APEX_JSON.write(''vacaciones'', l_vacas);
    APEX_JSON.write(''permisos'', l_perm);
    APEX_JSON.write(''incapacidades'', l_incap);
    APEX_JSON.write(''incidencias_activas'', l_incid);
    APEX_JSON.close_object;
    APEX_JSON.close_object;
END;'
    );
    
    COMMIT;
END;
/
